services:
  db:
    container_name: "db_mysql"
    build:
      dockerfile: Database.Dockerfile
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 1s
      retries: 20
  backend:
    container_name: "backend"
    depends_on:
      db:
        condition:
          service_healthy
    build:
      dockerfile: Backend.Dockerfile
    entrypoint: "app"
    healthcheck:
      test: "curl -f http://localhost:8080/ping"
      timeout: 5s
      retries: 10
    environment:
      PORT: "8080"
      DB_HOST: "db_mysql"
      DB_PORT: "3306"
    ports:
      - "8080:8080"
