services:
  db:
    container_name: "db_mysql"
    build:
      dockerfile: Database.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "weather_database"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  backend:
    container_name: "backend"
    depends_on:
      db:
        condition:
          service_healthy
    build:
      dockerfile: Backend.Dockerfile
    entrypoint: "app"
